{
 "title": "Sweb Scoreboard Monitor",
 "tags": [
  "scoreboard",
  "influxdb"
 ],
 "time": { "from": "now-1y", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "bucket",
    "label": "Semester",
    "query": "import \"strings\"\n\nbuckets()\n  |> filter(fn: (r) => r.name =~ /^scoreboard-(ss|ws)[0-9]{4}$/)\n  |> map(fn: (r) => ({_value: r.name, semester: strings.substring(v: r.name, start: 13, end: 17) + (if strings.hasPrefix(v: r.name, prefix: \"scoreboard-ws\") then \"1\" else \"0\")}))\n  |> sort(columns: [\"semester\"], desc: true)\n  |> keep(columns: [\"_value\"])"
   },
   {
    "name": "team_id",
    "label": "teamID",
    "query": "import \"influxdata/influxdb/schema\"\nschema.tagValues(bucket: \"${bucket}\", tag: \"team_id\", predicate: (r) => r._measurement == \"team_scoreboard\", start: time(v: 0))"
   },
   {
    "name": "submission_type",
    "label": "SubmissionID",
    "query": {
     "query": "  import \"influxdata/influxdb/schema\"\n  schema.tagValues(bucket: \"${bucket}\", tag: \"submission_type\", predicate: (r) => r._measurement == \"team_scoreboard\", start: time(v: 0))"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Number of Tags per Submission",
   "type": "barchart",
   "description": "change the SubmissionID at the top to choose specific Submission Tag.",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 0 },
   "targets": [
    {
     "query": " from(bucket: \"${bucket}\")\n    |> range(start: 0)\n    |> filter(fn: (r) => r._measurement == \"team_scoreboard\" and r._field == \"rank\")\n    |> filter(fn: (r) => exists r.submission_type and r.submission_type =~ /^${submission_type:regex}$/)\n    |> filter(fn: (r) => r.submission1 == \"OK\")\n    |> group(columns: [\"submission_type\", \"team_id\"])\n    |> last()\n    |> group(columns: [\"submission_type\"])\n    |> count()\n    |> map(fn: (r) => ({_time: now(), _field: \"OK Teams\", submission_type: r.submission_type, _value: r._value}))\n    |> group()"
    },
    {
     "query": "from(bucket: \"${bucket}\")\n    |> range(start: 0)\n    |> filter(fn: (r) => r._measurement == \"team_scoreboard\" and r._field == \"rank\")\n    |> filter(fn: (r) => exists r.submission_type and r.submission_type =~ /^${submission_type:regex}$/)\n    |> group(columns: [\"submission_type\", \"team_id\"])\n    |> last()\n    |> group(columns: [\"submission_type\"])\n    |> count()\n    |> map(fn: (r) => ({_time: now(), _field: \"Total Teams\", submission_type: r.submission_type, _value: r._value}))\n    |> group()"
    }
   ]
  },
  {
   "title": "Current Submission Tag",
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 9, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "  from(bucket: \"${bucket}\")\n    |> range(start: 0)\n    |> filter(fn: (r) => r._measurement == \"team_scoreboard\" and r._field == \"rank\")\n    |> last()\n    |> group()\n    |> sort(columns: [\"_time\"])\n    |> last()\n    |> map(fn: (r) => ({_time: r._time, _value: r.submission_type}))"
    }
   ]
  },
  {
   "title": "Tags over time",
   "type": "timeseries",
   "description": "shows the amount of tagged submissions over time.",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 0 },
   "targets": [
    {
     "query": "  from(bucket: \"${bucket}\")\n    |> range(start: time(v: int(v: v.timeRangeStart) - int(v: 35m)), stop: v.timeRangeStop)\n    |> filter(fn: (r) => r._measurement == \"team_scoreboard\" and r._field == \"rank\")\n    |> filter(fn: (r) => exists r.submission_type and r.submission_type =~ /^${submission_type:regex}$/)\n    |> filter(fn: (r) => r.submission1 == \"OK\")\n    |> group(columns: [\"submission_type\", \"team_id\"])\n    |> aggregateWindow(every: v.windowPeriod, period: 35m, fn: last, createEmpty: false)\n    |> group(columns: [\"submission_type\"])\n    |> aggregateWindow(every: v.windowPeriod, fn: count, createEmpty: false)\n    |> filter(fn: (r) => r._value > 0)"
    }
   ]
  },
  {
   "title": "Age of current submissionID",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 9, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "currentType = from(bucket: \"${bucket}\")\n    |> range(start: 0)\n    |> filter(fn: (r) => r._measurement == \"team_scoreboard\" and r._field == \"rank\")\n    |> last()\n    |> group()\n    |> sort(columns: [\"_time\"])\n    |> last()\n    |> findRecord(fn: (key) => true, idx: 0)\n\n  from(bucket: \"${bucket}\")\n    |> range(start: 0)\n    |> filter(fn: (r) => r._measurement == \"team_scoreboard\" and r._field == \"rank\")\n    |> filter(fn: (r) => r.submission_type == currentType.submission_type)\n    |> group()\n    |> first()\n    |> map(fn: (r) => ({\n        _time: now(),\n        _value: float(v: uint(v: now()) - uint(v: r._time)) / 1000000000.0,\n        _field: \"active_since\"\n    }))"
    },
    {
     "query": " currentType = from(bucket: \"${bucket}\")\n    |> range(start: 0)\n    |> filter(fn: (r) => r._measurement == \"team_scoreboard\" and r._field == \"rank\")\n    |> last()\n    |> group()\n    |> sort(columns: [\"_time\"])\n    |> last()\n    |> findRecord(fn: (key) => true, idx: 0)\n\n  from(bucket: \"${bucket}\")\n    |> range(start: 0)\n    |> filter(fn: (r) => r._measurement == \"team_scoreboard\" and r._field == \"rank\")\n    |> filter(fn: (r) => r.submission_type == currentType.submission_type)\n    |> group()\n    |> first()\n    |> map(fn: (r) => ({\n        _time: now(),\n        _value: float(v: uint(v: r._time)) / 1000000.0,\n        _field: \"first_seen\"\n    }))"
    }
   ]
  },
  {
   "title": "Last Scrape Age",
   "type": "stat",
   "description": "scrapes for changes every 60 seconds. Global update (regardless of changes) every 30m.",
   "gridPos": { "h": 3, "w": 6, "x": 9, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: -7d)\n  |> filter(fn: (r) => r._measurement == \"scraper_health\" and r._field == \"rows_parsed\")\n  |> group()\n  |> last()\n  |> map(fn: (r) => ({_time: now(), _value: float(v: uint(v: now()) - uint(v: r._time)) / 1000000000.0, _field: \"last_scrape_age_seconds\"}))"
    }
   ]
  },
  {
   "title": "Rank Over Time",
   "type": "timeseries",
   "description": "empty Lines/Missing ranks are due to anonymous teams which are not tracked here.",
   "gridPos": { "h": 18, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"team_scoreboard\" and r._field == \"rank\")\n  |> filter(fn: (r) => exists r.team_id and r.team_id =~ /^${team_id:regex}$/)\n  |> filter(fn: (r) => not exists r.submission_type or r.submission_type =~ /^${submission_type:regex}$/)     \n  |> group(columns: [\"display_name\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: true)\n  |> yield(name: \"rank\")"
    }
   ]
  },
  {
   "title": "Testsystem running progress",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"team_scoreboard\" and r._field == \"queue_running_percent\")\n  |> filter(fn: (r) => exists r.team_id and r.team_id =~ /^${team_id:regex}$/)\n  |> group(columns: [\"display_name\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> map(fn: (r) => ({r with _field: r.display_name}))\n  |> keep(columns: [\"_time\", \"_value\", \"_field\"])\n  |> group(columns: [\"_field\"])"
    }
   ]
  },
  {
   "title": "Latest Standings For Selected Stable Teams",
   "type": "table",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 31 },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"team_scoreboard\")\n  |> filter(fn: (r) => exists r.team_id and r.team_id =~ /^${team_id:regex}$/)\n  |> filter(fn: (r) =>\n    r._field == \"rank\" or\n    r._field == \"score\" or\n    r._field == \"threads\" or\n    r._field == \"fork_exec\" or\n    r._field == \"swapping\" or\n    r._field == \"shm\" or\n    r._field == \"other\" or\n    r._field == \"avg_5d\" or\n    r._field == \"up_count\" or\n    r._field == \"tw\" or\n    r._field == \"perf\" or\n    r._field == \"build_ok\" or\n    r._field == \"boot_ok\"\n  )\n  |> group(columns: [\"team_id\", \"display_name\", \"_field\", \"submission1\"])\n  |> last()\n  |> pivot(\n    rowKey: [\"team_id\", \"display_name\", \"submission1\", \"_time\"],\n    columnKey: [\"_field\"],\n    valueColumn: \"_value\"\n  )\n  |> group()\n  |> keep(columns: [\n    \"rank\",\n    \"team_id\",\n    \"display_name\",\n    \"score\",\n    \"threads\",\n    \"fork_exec\",\n    \"swapping\",\n    \"shm\",\n    \"other\",\n    \"avg_5d\",\n    \"up_count\",\n    \"tw\",\n    \"perf\",\n    \"build_ok\",\n    \"boot_ok\",\n    \"submission1\",\n    \"_time\"\n  ])\n  |> sort(columns: [\"rank\"])"
    }
   ]
  },
  {
   "title": "Score Over Time",
   "type": "timeseries",
   "gridPos": { "h": 18, "w": 24, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"team_scoreboard\" and r._field == \"score\")\n  |> filter(fn: (r) => exists r.team_id and r.team_id =~ /^${team_id:regex}$/)\n  |> filter(fn: (r) => not exists r.submission_type or r.submission_type =~ /^${submission_type:regex}$/)     \n  |> group(columns: [\"display_name\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: true)\n  |> yield(name: \"score\")"
    }
   ]
  },
  {
   "title": "Stack Health",
   "type": "alertlist",
   "description": "Shows health of the whole stack and the Testystem Website. (Alerting is set to send me a push notification via Discord, so bare with me, doing this in my free time) ",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 54 }
  }
 ]
}